-- Attendance Phase 2 — PIN-based pickup + curbside time slots.
--
-- Use case: a parent designates Grandma Sue as an authorized pickup
-- person. She doesn't have a parent-portal account. The school has a
-- "kiosk" pickup page where she enters her PIN + signs + picks the
-- child + selects a curbside time slot. The PIN is set by the parent in
-- the parent portal.

ALTER TABLE pickup_persons
  ADD COLUMN IF NOT EXISTS pin_hash text,            -- 'salt:scrypt-hex' format; NULL = no PIN set
  ADD COLUMN IF NOT EXISTS pin_set_at timestamptz,
  ADD COLUMN IF NOT EXISTS pin_expires_at timestamptz, -- NULL = never expires (recurring authorization)
  ADD COLUMN IF NOT EXISTS is_temporary boolean NOT NULL DEFAULT false;

-- Partial index for fast PIN lookup (small filtered set: just
-- pickup_persons in this school with a PIN currently set).
CREATE INDEX IF NOT EXISTS idx_pickup_persons_with_pin
  ON pickup_persons (school_id)
  WHERE pin_hash IS NOT NULL AND active = true;

-- Curbside time slot — when the pickup happens at the curb at one of
-- the school's published windows. NULL = not curbside, OR curbside but
-- pre-Phase-2 row that didn't record a slot.
ALTER TABLE attendance_events
  ADD COLUMN IF NOT EXISTS curbside_slot text;

-- Rate-limit / audit table for PIN attempts. Prevents brute-forcing the
-- 6-digit space and records who tried (failed or successful).
CREATE TABLE IF NOT EXISTS pickup_pin_attempts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id uuid NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  pickup_person_id uuid REFERENCES pickup_persons(id) ON DELETE SET NULL,
  pin_prefix text,                       -- first 2 chars only, for audit/correlation w/o leaking the PIN
  succeeded boolean NOT NULL,
  attempted_at timestamptz NOT NULL DEFAULT now(),
  ip_address text,
  user_agent text
);

CREATE INDEX IF NOT EXISTS idx_pin_attempts_school_time
  ON pickup_pin_attempts (school_id, attempted_at DESC);
CREATE INDEX IF NOT EXISTS idx_pin_attempts_ip_recent
  ON pickup_pin_attempts (ip_address, attempted_at DESC);

COMMENT ON COLUMN pickup_persons.pin_hash IS
  '6-digit PIN stored as scrypt hash. Set/regenerated by a parent in the parent portal; verified at the school''s kiosk pickup page.';
COMMENT ON COLUMN attendance_events.curbside_slot IS
  'When curbside=true, which published time slot the pickup matched (e.g. ''12:00'', ''14:30'').';
